# Generated by Django 4.2.7 on 2024-02-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_job_description_report_newsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='revenue',
        ),
        migrations.AddField(
            model_name='report',
            name='projects',
            field=models.TextField(default='No projects found'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='website_url',
            field=models.URLField(default='/', max_length=1024),
            preserve_default=False,
        ),
    ]
