# Generated by Django 4.2.7 on 2024-02-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_report_revenue_report_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='overall_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='rating_distribution',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='top_reviews',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
