# Generated by Django 4.2.7 on 2024-02-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_report_overall_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='overall_rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='rating_distribution',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='top_reviews',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
