# Generated by Django 4.2.7 on 2024-02-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_report_overall_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
