# Generated by Django 4.2.7 on 2024-02-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_interview_interviewquestion_interviewanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
